version: "3"
services:
  nginx:
    restart: always
    image: "sagi403/dbm-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  backend:
    image: "sagi403/dbm-backend"
    mem_limit: 128m
    hostname: backend
    environment:
      - HOST=$HOST
      - PORT=$PORT
      - APP_KEYS=$APP_KEYS
      - API_TOKEN_SALT=$API_TOKEN_SALT
      - ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET
      - TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT
      - DATABASE_CLIENT=$DATABASE_CLIENT
      - DATABASE_FILENAME=$DATABASE_FILENAME
      - JWT_SECRET=$JWT_SECRET
    ports:
      - "1337:1337"
  frontend:
    image: "sagi403/dbm-frontend"
    mem_limit: 128m
    hostname: frontend
    environment:
      - VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY
      - VITE_BASE_URL=$VITE_BASE_URL
